### ISSUE TITLE
Corner chunks don't render at all on classic servers

### ISSUE THREAD

**Issue by forkiesassds** [RaphiMC/ViaProxy#20]

**Comment by RaphiMC** [comment]
Sodium is known to have that issue: https://github.com/CaffeineMC/sodium-fabric/issues/1111
Use vanilla or Optifabric if this issue annoys you. I won't be fixing issue of other devs.

**Comment by forkiesassds** [comment]
This issue also happens on bedrock, via Geyser.

**Comment by RaphiMC** [comment]
Still not my problem as it works fine in vanilla. Anything that breaks in non vanilla enironments is the fault of other devs

**Comment by forkiesassds** [comment]
Shouldn't you at least bother supporting the most commonly used mods or software that people use on a daily basis instead of saying "use vanilla, WAI"

**Comment by RaphiMC** [comment]
I would if it was easy, but fixing this on my side will be awful. I already fixed most of the issue because the issue was that the whole rows of border chunks were invisible. Here is a mod for 1.19.3 which fixes it for sodium: https://cdn.discordapp.com/attachments/1060287409322983475/1076117399666970644/sodium-corner-chunk-fix.jar

**Comment by forkiesassds** [comment]
Did you try sending chunks full of air at the neighbors of the corner chunks? Or that didn't help and will require an entirely different solution

**Comment by RaphiMC** [comment]
This does fix it, but it also causes an extra amount of lag on the client because of all the useless chunk updates. Fixing this only for classic worlds would be possible, but I don't see how its my job to bloat my code with a fix that is mostly useless and only applies to a mod which broke a vanilla feature
