### ISSUE TITLE
[Question/Suggestion] ViaProxy/MinecraftAuth add supported mojang account login.

### ISSUE THREAD

**Issue by sheng-ri** [RaphiMC/ViaProxy#26]
Recently, I try use ViaProxy to join some server use [https://github.com/yushijinhun/authlib-injector](url)
But ViaProxy/MinecraftAuth only support Java MSA.
I know OpenAuthMod may can dael with it.
But I use [https://github.com/GeyserMC/MCProtocolLib](url) to join server, So it can't load fabric mod or forge mod.

Is this will support in the future?

**Comment by RaphiMC** [comment]
Mojang accounts aren't officially used anymore. You should try and add OpenAuthMod support to your program. Its really easy to do because you only need to handle one login custom payload packet which contains the server id hash. Here is the corresponding code: https://github.com/RaphiMC/OpenAuthMod/blob/master/Shared/src/main/java/net/raphimc/openauthmod/ModernOpenAuthModPlatform.java#L18

**Comment by sheng-ri** [comment]
I will try this, Thanks a lost.

**Comment by RaphiMC** [comment]
If you need help implementing it you can join my discord (Link in the README)
