### ISSUE TITLE
Entrypoint for starting via code

### ISSUE THREAD

**Issue by stashymane** [RaphiMC/ViaProxy#34]
I'm currently starting ViaProxy via the main function, for which I have to modify arguments as strings and launch it in a separate thread. Although this setup is only for testing/development, ould be nice to have an entry point when using it as a library instead of a separate proxy.

**Comment by RaphiMC** [comment]
What exactly is your use case? There might be a better way to do the thing you are trying to accomplish

**Comment by stashymane** [comment]
I'm running a Minestom server (which is not particularly supported by ViaVersion, but that's my problem), and I'd like to have both the proxy and server to run at the same time, at least for now.

**Comment by stashymane** [comment]
The better way would be to run a new task, but being able to manage both the Minestom & proxy thread is great - once once fails, I can immediately handle the situation.

**Comment by RaphiMC** [comment]
I see. Adding an entry point which doesn't require a String array isn't that easy because the options parser I use depends on having a String array. I think using it should be fine as I try to keep the CLI interface stable between versions. Make sure to use the long form of the arguments (--whatever)

**Comment by RaphiMC** [comment]
I assume everything should be clear now. If you have further questions just comment on this issue
